version: 2.1

workflows:
  ci:
    jobs:
      - selfcheck

jobs:
  selfcheck:
    docker:
      - image: gcc
    steps:
      - checkout
      - run: make
      - run: mkdir -p test-results/junit/
      - run: build/ghost-sh --self-check --junit-xml test-results/junit/results.xml
      - store_test_results:
          path: test-results
